// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQh_aimW9fJ7v07BYVxyjw9vDJ6RYmycQ',
    appId: '1:996932235465:web:c6cd4667ac4b3803131d18',
    messagingSenderId: '996932235465',
    projectId: 'diet-planner-3f340',
    authDomain: 'diet-planner-3f340.firebaseapp.com',
    storageBucket: 'diet-planner-3f340.firebasestorage.app',
    measurementId: 'G-3PXNCBEELE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANWfz0GQE17jpfc1pnU3EQTuIJj5VSA7w',
    appId: '1:996932235465:android:a765742d4901c0ec131d18',
    messagingSenderId: '996932235465',
    projectId: 'diet-planner-3f340',
    storageBucket: 'diet-planner-3f340.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcp1Wn0ABul6WTmrG_o4-svuT4nQ5_iPE',
    appId: '1:996932235465:ios:4a20671f45ebfe3a131d18',
    messagingSenderId: '996932235465',
    projectId: 'diet-planner-3f340',
    storageBucket: 'diet-planner-3f340.firebasestorage.app',
    iosBundleId: 'com.example.dietplanner',
  );
}
